apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: tanzu-spring-petclinic
  labels:
    app.kubernetes.io/part-of: tanzu-spring-petclinic
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: tanzu-spring-petclinic
spec:
  template:
    metadata:
      annotations:
        conventions.apps.tanzu.vmware.com/applied-conventions: ""
        developer.conventions/target-containers: workload
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: tanzu-spring-petclinic
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: tanzu-spring-petclinic
    spec:
      containers:
      - env:
        - name: JAVA_TOOL_OPTIONS
        image: tanzuapplicationregistry.azurecr.io/supply-chain/tanzu-spring-petclinic-default@sha256:2a4f742feea8492bf4cd0407d46d409fc3c958b6ba9d0bf0fe1b50a1726aac77
        name: workload
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

