apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tanzu-spring-petclinic
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: tanzu-spring-petclinic
spec:
  source:
    git:
      url: https://github.com/nycpivot/tanzu-spring-petclinic
      ref:
        branch: main
        tag: tap-1.0
